services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows backend to control Docker
    restart: unless-stopped

  ui:
    image: lissy93/dashy
    ports:
      - "8080:8080"  # Expose Dashy UI on port 8080
    volumes:
      - ./ui/config.yaml:/app/user-data/conf.yml
      - ./ui/styles/user-defined-themes.scss:/app/src/styles/user-defined-themes.scss
      - ./assets:/app/user-data/assets
    restart: unless-stopped