services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows backend to control Docker
    restart: unless-stopped

  ui:
    image: lissy93/dashy
    ports:
      - "8080:8080"  # Expose Dashy UI on port 8080
    volumes:
      - ./ui/config.yaml:/user-data/conf.yml  # Mount custom configuration file (optional)
    restart: unless-stopped