name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  install:
    # Define a matrix to run on multiple operating systems
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    # Use the OS defined in the matrix
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Run the install script
      - name: Run install.sh
        run: cd bin && ./install.sh -v -f