name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["CD"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Download all artifacts from the CD workflow
      - name: Download all artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: CD.yml
          workflow_conclusion: success
          path: ./artifacts

      # Setup Git for deployment
      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Add new or updated artifacts to the gh-pages branch
      - name: Deploy to GitHub Pages
        run: |
          git fetch --depth=1 origin gh-pages
          git checkout gh-pages
          cp -R ./artifacts/* ./ # Copy new artifacts
          git add .
          git commit -m "Deploy from CD workflow artifacts [skip ci]" || echo "No changes to commit"
          git push origin gh-pages